services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: product-service-db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql-data:/var/lib/mysql

  #  product-service:
  #      image: product-service:latest
  #      container_name: product-service
  #      ports:
  #          - "8080:8080"
  #      depends_on:
  #          - mysql
  #      environment:
  #          SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/product-service-db?useSSL=false
  #          SPRING_DATASOURCE_USERNAME: admin
  #          SPRING_DATASOURCE_PASSWORD: password
  #          SPRING_JPA_HIBERNATE_DDL_AUTO: create
  #          SPRING_JPA_SHOW_SQL: true
  #          SPRING_JPS_FORMAT_SQL: true
  #          SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8InnoDBDialect

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"