application:
  title: API Gateway
  version: 1.0.0
spring:
  application:
    name: api-gateway
  # Product Serive Routes
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/v1/inventory
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders
        - id: discovery-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: discovery-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
  security:

    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/e-commerce-ms
      authorizationserver:
        endpoint:
          token-uri: http://localhost:8181/realms/e-commerce-ms/protocol/openid-connect/token
          oidc:
            client-registration-uri: http://localhost:8181/realms/e-commerce-ms/clients-registrations/openid-connect

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka/

logging:
  level:
    root: INFO
    org:
      route.RouteDefinitionRouteLocator: INFO
      springframework:
        cloud:
          gateway: TRACE
