#debug: true
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/order-service-db?createDatabaseIfNotExist=true&useSSL=false
    #    url: mysql://localhost:3306/order-service-db?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#logging:
#  level:
#    web:
#      - debug
#      - info
#      - error
#      - warn
#      - trace
#      - fatal
server:
  port: 0
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
