#debug: true
application:
  title: Order Service
  version: 1.0.0
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/order-service-db?createDatabaseIfNotExist=true&useSSL=false
    #    url: mysql://localhost:3306/order-service-db?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

# Circuit Breaker
#logging:
#  level:
#    web:
#      - debug
#      - info
#      - error
#      - warn
#      - trace
#      - fatal
server:
  port: 0
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  health:
    circuitbreakers:
      enabled: true

# Resilience4j Configurations
resilience4j:
  timelimiter:
    instances:
        inventory:
            timeoutDuration: 5s
  circuitbreaker:
    instances:
      inventory:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        minimumNumberOfCalls: 5
  retry:
    instances:
        inventory:
            waitDuration: 5s
            maxAttempts: 3
#        recordExceptions:
#          - java.io.IOException
#          - java.util.concurrent.TimeoutException
#          - java.lang.Exception
#        ignoreExceptions:
#          - java.lang.RuntimeException
#          - java.lang.Exception
